name: 'first pipeline'


on:
  push:
    branches:
      - master
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull changes from repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
      
      - name: Install dependecy
        run: npm install

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./**

